# Generated by Django 5.2.6 on 2025-09-19 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quadro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título do Quadro')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quadros', to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Cartão')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('quadro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to='core.quadro')),
            ],
        ),
    ]
