# Generated by Django 5.2.6 on 2025-09-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_quadro_cartao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='status',
            field=models.CharField(choices=[('fazer', 'A Fazer'), ('andamento', 'Em Andamento'), ('concluido', 'Concluído')], default='fazer', max_length=20, verbose_name='Status'),
        ),
    ]
