# Generated by Django 5.2.6 on 2025-09-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cartao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='status',
            field=models.CharField(choices=[('fixo', 'Informações Fixas'), ('fazer', 'A Fazer'), ('andamento', 'Em Andamento'), ('concluido', 'Concluído')], default='fazer', max_length=20, verbose_name='Status'),
        ),
    ]
