# Generated by Django 5.2.6 on 2025-09-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cartao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='anexos/', verbose_name='Anexo (PDF, Imagem, etc.)'),
        ),
    ]
