# Generated by Django 5.2.5 on 2025-11-16 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cartao_anexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('agendamento', 'Agendamento'), ('pendencia', 'Pendência')], max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluído')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('quadro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='core.quadro')),
            ],
            options={
                'ordering': ['concluido', 'data_criacao'],
            },
        ),
    ]
