# Generated by Django 5.2.5 on 2025-11-06 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0044_subscription_has_commercial_module_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EMITIDA', 'Emitida'), ('CANCELADA', 'Cancelada'), ('ERRO', 'Erro de Emissão')], default='PENDENTE', max_length=10)),
                ('numero_nf', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número da NF-e')),
                ('serie', models.CharField(blank=True, max_length=5, null=True, verbose_name='Série')),
                ('chave_acesso', models.CharField(blank=True, db_index=True, max_length=44, null=True, verbose_name='Chave de Acesso')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_emissao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('arquivo_xml', models.FileField(blank=True, null=True, upload_to='notas_fiscais/xml/%Y/%m/')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='notas_fiscais/pdf/%Y/%m/', verbose_name='DANFE (PDF)')),
                ('mensagem_erro', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro/Retorno')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.cliente', verbose_name='Cliente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário da Licença')),
                ('venda', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nota_fiscal', to='accounts.venda')),
            ],
            options={
                'verbose_name': 'Nota Fiscal',
                'verbose_name_plural': 'Notas Fiscais',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
