# Generated by Django 5.2.5 on 2025-11-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas_fiscais', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notafiscal',
            name='arquivo_pdf',
        ),
        migrations.RemoveField(
            model_name='notafiscal',
            name='arquivo_xml',
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='ref_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID de Referência (API)'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='url_pdf',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL do DANFE (PDF)'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='url_xml',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL do XML'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('EMITIDA', 'Emitida'), ('CANCELADA', 'Cancelada'), ('ERRO', 'Erro de Emissão')], default='PENDENTE', max_length=15),
        ),
    ]
