# Generated by Django 5.2.5 on 2025-11-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas_fiscais', '0002_remove_notafiscal_arquivo_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='modelo',
            field=models.CharField(choices=[('NFE', 'Produto (NF-e)'), ('NFSE', 'Serviço (NFS-e)')], default='NFE', max_length=10),
        ),
    ]
