# Generated by Django 5.2.4 on 2025-07-26 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payableaccount',
            name='dre_area',
            field=models.CharField(choices=[('RECEITAS_BRUTAS', 'Receitas Brutas'), ('DEDUCAO_RECEITA_BRUTA', 'Dedução da Receita Bruta'), ('RECEITAS_LIQUIDAS', 'Receitas Líquidas'), ('CUSTOS_CSP_CMV', 'Custos - CSP/CMV'), ('LUCRO_BRUTO_MC', 'Lucro Bruto / Margem de AContribuição'), ('DESPESAS_OPERACIONAIS', 'Despesas Operacionais'), ('LUCRO_LIQUIDO_OPERACIONAL', 'Lucro Líquido Operacional'), ('NAO_OPERACIONAIS', 'Não Operacionais'), ('LUCRO_LIQUIDO_FINAL', 'Lucro Líquido Final'), ('PONTO_EQUILIBRIO', 'Ponto de Equilíbrio'), ('DISTRIBUICAO_LUCROS_SOCIOS', 'Distribuição de Lucros Sócios'), ('RESULTADO_FINAL', 'Resultado Final')], max_length=50),
        ),
        migrations.CreateModel(
            name='ReceivableAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dre_area', models.CharField(choices=[('RECEITAS_BRUTAS', 'Receitas Brutas'), ('DEDUCAO_RECEITA_BRUTA', 'Dedução da Receita Bruta'), ('RECEITAS_LIQUIDAS', 'Receitas Líquidas'), ('CUSTOS_CSP_CMV', 'Custos - CSP/CMV'), ('LUCRO_BRUTO_MC', 'Lucro Bruto / Margem de AContribuição'), ('DESPESAS_OPERACIONAIS', 'Despesas Operacionais'), ('LUCRO_LIQUIDO_OPERACIONAL', 'Lucro Líquido Operacional'), ('NAO_OPERACIONAIS', 'Não Operacionais'), ('LUCRO_LIQUIDO_FINAL', 'Lucro Líquido Final'), ('PONTO_EQUILIBRIO', 'Ponto de Equilíbrio'), ('DISTRIBUICAO_LUCROS_SOCIOS', 'Distribuição de Lucros Sócios'), ('RESULTADO_FINAL', 'Resultado Final')], max_length=50)),
                ('payment_method', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('DEBITO', 'Débito'), ('CREDITO', 'Crédito')], max_length=20)),
                ('occurrence', models.CharField(choices=[('AVULSO', 'Avulso'), ('RECORRENTE', 'Recorrente')], max_length=20)),
                ('recurrence_count', models.PositiveIntegerField(blank=True, null=True)),
                ('is_received', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
