# Generated by Django 5.2.4 on 2025-07-26 03:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_payableaccount_dre_area_receivableaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payableaccount',
            name='cost_type',
            field=models.CharField(choices=[('FIXO', 'Fixo'), ('VARIAVEL', 'Variável')], default='FIXO', max_length=20),
        ),
        migrations.AddField(
            model_name='payableaccount',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='payables/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='payableaccount',
            name='dre_area',
            field=models.CharField(choices=[('RECEITAS_BRUTAS', 'Receitas Brutas'), ('DEDUCAO_RECEITA_BRUTA', 'Dedução da Receita Bruta'), ('RECEITAS_LIQUIDAS', 'Receitas Líquidas'), ('CUSTOS_CSP_CMV', 'Custos - CSP/CMV'), ('LUCRO_BRUTO_MC', 'Lucro Bruto / Margem de Contribuição'), ('DESPESAS_OPERACIONAIS', 'Despesas Operacionais'), ('LUCRO_LIQUIDO_OPERACIONAL', 'Lucro Líquido Operacional'), ('NAO_OPERACIONAIS', 'Não Operacionais'), ('LUCRO_LIQUIDO_FINAL', 'Lucro Líquido Final'), ('PONTO_EQUILIBRIO', 'Ponto de Equilíbrio'), ('DISTRIBUICAO_LUCROS_SOCIOS', 'Distribuição de Lucros Sócios'), ('RESULTADO_FINAL', 'Resultado Final')], max_length=50),
        ),
        migrations.AlterField(
            model_name='receivableaccount',
            name='dre_area',
            field=models.CharField(choices=[('RECEITAS_BRUTAS', 'Receitas Brutas'), ('DEDUCAO_RECEITA_BRUTA', 'Dedução da Receita Bruta'), ('RECEITAS_LIQUIDAS', 'Receitas Líquidas'), ('CUSTOS_CSP_CMV', 'Custos - CSP/CMV'), ('LUCRO_BRUTO_MC', 'Lucro Bruto / Margem de Contribuição'), ('DESPESAS_OPERACIONAIS', 'Despesas Operacionais'), ('LUCRO_LIQUIDO_OPERACIONAL', 'Lucro Líquido Operacional'), ('NAO_OPERACIONAIS', 'Não Operacionais'), ('LUCRO_LIQUIDO_FINAL', 'Lucro Líquido Final'), ('PONTO_EQUILIBRIO', 'Ponto de Equilíbrio'), ('DISTRIBUICAO_LUCROS_SOCIOS', 'Distribuição de Lucros Sócios'), ('RESULTADO_FINAL', 'Resultado Final')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='payableaccount',
            index=models.Index(fields=['due_date'], name='accounts_pa_due_dat_572560_idx'),
        ),
        migrations.AddIndex(
            model_name='receivableaccount',
            index=models.Index(fields=['due_date'], name='accounts_re_due_dat_fc5a1a_idx'),
        ),
    ]
