# Generated by Django 5.2.4 on 2025-07-31 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_payableaccount_cost_type_payableaccount_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payableaccount',
            name='dre_area',
            field=models.CharField(choices=[('DEDUCAO', 'Dedução da Receita Bruta'), ('CUSTOS', 'Custos CSP/CMV'), ('OPERACIONAL', 'Despesas Operacionais'), ('NAO_OPERACIONAL', 'Não Operacional'), ('DISTRIBUICAO', 'Distribuição de Lucro Sócios')], max_length=50),
        ),
        migrations.AlterField(
            model_name='receivableaccount',
            name='dre_area',
            field=models.CharField(choices=[('DEDUCAO', 'Dedução da Receita Bruta'), ('CUSTOS', 'Custos CSP/CMV'), ('OPERACIONAL', 'Despesas Operacionais'), ('NAO_OPERACIONAL', 'Não Operacional'), ('DISTRIBUICAO', 'Distribuição de Lucro Sócios')], max_length=50),
        ),
    ]
