# Generated by Django 5.2.4 on 2025-07-31 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_payableaccount_dre_area_and_more'),
    ]

    operations = [
    ]
