# Generated by Django 5.2.4 on 2025-07-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20250731_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payableaccount',
            name='dre_area',
            field=models.CharField(choices=[('DEDUCAO', 'Dedução da Receita Bruta'), ('CUSTOS', 'Custos CSP/CMV'), ('OPERACIONAL', 'Despesas Operacionais'), ('NAO_OPERACIONAL', 'Não Operacional'), ('DISTRIBUICAO', 'Distribuição de Lucro Sócios'), ('BRUTA', 'Receitas Brutas')], max_length=50),
        ),
        migrations.AlterField(
            model_name='receivableaccount',
            name='dre_area',
            field=models.CharField(choices=[('DEDUCAO', 'Dedução da Receita Bruta'), ('CUSTOS', 'Custos CSP/CMV'), ('OPERACIONAL', 'Despesas Operacionais'), ('NAO_OPERACIONAL', 'Não Operacional'), ('DISTRIBUICAO', 'Distribuição de Lucro Sócios'), ('BRUTA', 'Receitas Brutas')], max_length=50),
        ),
    ]
