# Generated by Django 5.2.4 on 2025-08-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_ofximport_payableaccount_ofx_import_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payableaccount',
            name='dre_area',
            field=models.CharField(choices=[('NAO_CONSTAR', 'Não constar DRE'), ('DEDUCAO', 'Dedução da Receita Bruta'), ('CUSTOS', 'Custos CSP/CMV'), ('OPERACIONAL', 'Despesas Operacionais'), ('NAO_OPERACIONAL', 'Não Operacional'), ('DISTRIBUICAO', 'Distribuição de Lucro Sócios'), ('BRUTA', 'Receitas Brutas'), ('NAO_CONSTAR', 'Não constar na DRE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='receivableaccount',
            name='dre_area',
            field=models.CharField(choices=[('NAO_CONSTAR', 'Não constar DRE'), ('DEDUCAO', 'Dedução da Receita Bruta'), ('CUSTOS', 'Custos CSP/CMV'), ('OPERACIONAL', 'Despesas Operacionais'), ('NAO_OPERACIONAL', 'Não Operacional'), ('DISTRIBUICAO', 'Distribuição de Lucro Sócios'), ('BRUTA', 'Receitas Brutas'), ('NAO_CONSTAR', 'Não constar na DRE')], max_length=50),
        ),
    ]
