# Generated by Django 5.2.4 on 2025-08-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_receivableaccount_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payableaccount',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Pagamento'),
        ),
    ]
