# Generated by Django 5.2.4 on 2025-08-11 17:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_payableaccount_payment_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payableaccount',
            options={'ordering': ['-due_date']},
        ),
        migrations.AlterModelOptions(
            name='receivableaccount',
            options={'ordering': ['-due_date']},
        ),
        migrations.RemoveField(
            model_name='ofximport',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receivableaccount',
            name='regiao',
            field=models.CharField(blank=True, help_text='Ex: São Paulo, Minas Gerais', max_length=100, null=True, verbose_name='Região do Cliente'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payableaccount',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='payableaccount',
            name='bank_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.bankaccount', verbose_name='Conta Bancária'),
        ),
        migrations.AlterField(
            model_name='payableaccount',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='payableaccount',
            name='cost_type',
            field=models.CharField(choices=[('FIXO', 'Fixo'), ('VARIAVEL', 'Variável')], default='FIXO', max_length=20, verbose_name='Tipo de Custo'),
        ),
        migrations.AlterField(
            model_name='payableaccount',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='payableaccount',
            name='dre_area',
            field=models.CharField(choices=[('NAO_CONSTAR', 'Não constar DRE'), ('DEDUCAO', 'Dedução da Receita Bruta'), ('CUSTOS', 'Custos CSP/CMV'), ('OPERACIONAL', 'Despesas Operacionais'), ('NAO_OPERACIONAL', 'Não Operacional'), ('DISTRIBUICAO', 'Distribuição de Lucro Sócios'), ('BRUTA', 'Receitas Brutas')], max_length=50, verbose_name='Área DRE'),
        ),
        migrations.AlterField(
            model_name='payableaccount',
            name='due_date',
            field=models.DateField(verbose_name='Data de Vencimento'),
        ),
        migrations.AlterField(
            model_name='payableaccount',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='payables/%Y/%m/%d/', verbose_name='Anexo'),
        ),
        migrations.AlterField(
            model_name='payableaccount',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Está Pago?'),
        ),
        migrations.AlterField(
            model_name='payableaccount',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome da Despesa'),
        ),
        migrations.AlterField(
            model_name='payableaccount',
            name='occurrence',
            field=models.CharField(choices=[('AVULSO', 'Avulso'), ('RECORRENTE', 'Recorrente')], max_length=20, verbose_name='Ocorrência'),
        ),
        migrations.AlterField(
            model_name='payableaccount',
            name='payment_method',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('DEBITO', 'Débito'), ('CREDITO', 'Crédito')], max_length=20, verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='payableaccount',
            name='recurrence_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Qtd. Recorrências'),
        ),
        migrations.AlterField(
            model_name='receivableaccount',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Total da Venda'),
        ),
        migrations.AlterField(
            model_name='receivableaccount',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.category', verbose_name='Categoria da Venda'),
        ),
        migrations.AlterField(
            model_name='receivableaccount',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição da Venda'),
        ),
        migrations.AlterField(
            model_name='receivableaccount',
            name='dre_area',
            field=models.CharField(choices=[('NAO_CONSTAR', 'Não constar DRE'), ('DEDUCAO', 'Dedução da Receita Bruta'), ('CUSTOS', 'Custos CSP/CMV'), ('OPERACIONAL', 'Despesas Operacionais'), ('NAO_OPERACIONAL', 'Não Operacional'), ('DISTRIBUICAO', 'Distribuição de Lucro Sócios'), ('BRUTA', 'Receitas Brutas')], default='BRUTA', max_length=50),
        ),
        migrations.AlterField(
            model_name='receivableaccount',
            name='due_date',
            field=models.DateField(verbose_name='Data de Vencimento'),
        ),
        migrations.AlterField(
            model_name='receivableaccount',
            name='is_received',
            field=models.BooleanField(default=False, verbose_name='Recebido?'),
        ),
        migrations.AlterField(
            model_name='receivableaccount',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome do Cliente/Venda'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('user', 'name')},
        ),
        migrations.CreateModel(
            name='ProdutoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Produto/Serviço')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Preço Unitário Padrão')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Sistema')),
            ],
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Preço Unitário (na venda)')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_venda', to='accounts.receivableaccount')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.produtoservico', verbose_name='Produto/Serviço')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Vendedor')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Sistema')),
            ],
        ),
        migrations.AddField(
            model_name='receivableaccount',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.vendedor', verbose_name='Vendedor'),
        ),
    ]
