# Generated by Django 5.2.4 on 2025-08-11 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_payableaccount_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtoservico',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='receivableaccount',
            name='vendedor',
        ),
        migrations.AlterModelOptions(
            name='payableaccount',
            options={},
        ),
        migrations.AlterModelOptions(
            name='receivableaccount',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='receivableaccount',
            name='regiao',
        ),
        migrations.AddField(
            model_name='ofximport',
            name='bank_name',
            field=models.CharField(default='Banco Temporário', max_length=100),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='payableaccount',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payableaccount',
            name='bank_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.bankaccount'),
        ),
        migrations.AlterField(
            model_name='payableaccount',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.category'),
        ),
        migrations.AlterField(
            model_name='payableaccount',
            name='cost_type',
            field=models.CharField(choices=[('FIXO', 'Fixo'), ('VARIAVEL', 'Variável')], default='FIXO', max_length=20),
        ),
        migrations.AlterField(
            model_name='payableaccount',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='payableaccount',
            name='dre_area',
            field=models.CharField(choices=[('NAO_CONSTAR', 'Não constar DRE'), ('DEDUCAO', 'Dedução da Receita Bruta'), ('CUSTOS', 'Custos CSP/CMV'), ('OPERACIONAL', 'Despesas Operacionais'), ('NAO_OPERACIONAL', 'Não Operacional'), ('DISTRIBUICAO', 'Distribuição de Lucro Sócios'), ('BRUTA', 'Receitas Brutas')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payableaccount',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payableaccount',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='payables/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='payableaccount',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payableaccount',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='payableaccount',
            name='occurrence',
            field=models.CharField(choices=[('AVULSO', 'Avulso'), ('RECORRENTE', 'Recorrente')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payableaccount',
            name='payment_method',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('DEBITO', 'Débito'), ('CREDITO', 'Crédito')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payableaccount',
            name='recurrence_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receivableaccount',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='receivableaccount',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.category'),
        ),
        migrations.AlterField(
            model_name='receivableaccount',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='receivableaccount',
            name='dre_area',
            field=models.CharField(choices=[('NAO_CONSTAR', 'Não constar DRE'), ('DEDUCAO', 'Dedução da Receita Bruta'), ('CUSTOS', 'Custos CSP/CMV'), ('OPERACIONAL', 'Despesas Operacionais'), ('NAO_OPERACIONAL', 'Não Operacional'), ('DISTRIBUICAO', 'Distribuição de Lucro Sócios'), ('BRUTA', 'Receitas Brutas')], max_length=50),
        ),
        migrations.AlterField(
            model_name='receivableaccount',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='receivableaccount',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='receivableaccount',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='ItemVenda',
        ),
        migrations.DeleteModel(
            name='ProdutoServico',
        ),
        migrations.DeleteModel(
            name='Vendedor',
        ),
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
