# Generated by Django 5.2.4 on 2025-08-12 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_ofximport_bank_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payableaccount',
            name='payment_method',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('DEBITO', 'Débito'), ('CREDITO', 'Crédito'), ('BOLETO', 'Boleto')], max_length=20),
        ),
        migrations.AlterField(
            model_name='receivableaccount',
            name='payment_method',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('DEBITO', 'Débito'), ('CREDITO', 'Crédito'), ('BOLETO', 'Boleto')], max_length=20),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('endereco', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('PRODUTO', 'Produto'), ('SERVICO', 'Serviço')], default='PRODUTO', max_length=10)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque_atual', models.IntegerField(default=0, help_text='Apenas para produtos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateTimeField(auto_now_add=True)),
                ('valor_total_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('desconto_geral', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_total_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='FINALIZADA', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.cliente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PagamentoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('DEBITO', 'Débito'), ('CREDITO', 'Crédito'), ('BOLETO', 'Boleto')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('parcelas', models.PositiveIntegerField(default=1)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='accounts.venda')),
            ],
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto_item', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.produtoservico')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='accounts.venda')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('comissao_percentual', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='venda',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.vendedor'),
        ),
    ]
