# Generated by Django 5.2.5 on 2025-08-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20250817_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='cidade',
            field=models.CharField(default='Não informado', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='estado',
            field=models.CharField(default='NI', max_length=2),
            preserve_default=False,
        ),
    ]
