# Generated by Django 5.2.5 on 2025-09-11 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaFaturamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_ano', models.DateField(verbose_name='Mês e Ano da Meta')),
                ('valor_meta', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor da Meta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.vendedor', verbose_name='Vendedor (Opcional)')),
            ],
            options={
                'verbose_name': 'Meta de Faturamento',
                'verbose_name_plural': 'Metas de Faturamento',
                'ordering': ['-mes_ano', 'vendedor__nome'],
            },
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.AddConstraint(
            model_name='metafaturamento',
            constraint=models.UniqueConstraint(condition=models.Q(('vendedor__isnull', True)), fields=('user', 'mes_ano'), name='unique_company_goal_per_month'),
        ),
        migrations.AddConstraint(
            model_name='metafaturamento',
            constraint=models.UniqueConstraint(fields=('user', 'vendedor', 'mes_ano'), name='unique_seller_goal_per_month'),
        ),
    ]
