# Generated by Django 5.2.5 on 2025-10-01 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_metafaturamento_delete_empresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='payableaccount',
            name='dre_area',
            field=models.CharField(choices=[('NAO_CONSTAR', 'Não constar DRE'), ('DEDUCAO', 'Dedução da Receita Bruta'), ('CUSTOS', 'Custos CSP/CMV'), ('OPERACIONAL', 'Despesas Operacionais'), ('DEPRECIACAO', 'Depreciação e Amortização'), ('NAO_OPERACIONAL', 'Não Operacional'), ('TRIBUTACAO', 'IRPJ e CSLL (Tributação)'), ('DISTRIBUICAO', 'Distribuição de Lucro Sócios'), ('BRUTA', 'Receitas Brutas')], max_length=50),
        ),
        migrations.AlterField(
            model_name='receivableaccount',
            name='dre_area',
            field=models.CharField(choices=[('NAO_CONSTAR', 'Não constar DRE'), ('DEDUCAO', 'Dedução da Receita Bruta'), ('CUSTOS', 'Custos CSP/CMV'), ('OPERACIONAL', 'Despesas Operacionais'), ('DEPRECIACAO', 'Depreciação e Amortização'), ('NAO_OPERACIONAL', 'Não Operacional'), ('TRIBUTACAO', 'IRPJ e CSLL (Tributação)'), ('DISTRIBUICAO', 'Distribuição de Lucro Sócios'), ('BRUTA', 'Receitas Brutas')], max_length=50),
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.estado')),
            ],
        ),
    ]
