# Generated by Django 5.2.5 on 2025-10-11 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivableaccount',
            name='bank_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.bankaccount'),
        ),
    ]
