# Generated by Django 5.2.5 on 2025-10-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_receivableaccount_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoservico',
            name='preco_custo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço de Custo'),
        ),
    ]
