# Generated by Django 5.2.5 on 2025-10-14 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_orcamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Precificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('perc_despesas_fixas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('perc_comissao', models.DecimalField(decimal_places=2, max_digits=5)),
                ('perc_impostos', models.DecimalField(decimal_places=2, max_digits=5)),
                ('perc_lucro', models.DecimalField(decimal_places=2, max_digits=5)),
                ('preco_venda_sugerido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.produtoservico')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Precificação',
                'verbose_name_plural': 'Registros de Precificação',
                'ordering': ['-created_at'],
            },
        ),
    ]
