# Generated by Django 5.2.5 on 2025-10-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_precificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='precificacao',
            name='is_price_updated',
            field=models.BooleanField(default=False, verbose_name='Preço Atualizado no Cadastro'),
        ),
    ]
