# Generated by Django 5.2.5 on 2025-10-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_orcamentovenda_itemorcamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentovenda',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITO', 'Aceito'), ('NEGADO', 'Negado'), ('CONVERTIDO', 'Convertido em Venda')], default='PENDENTE', max_length=10),
        ),
    ]
