# Generated by Django 5.2.5 on 2025-10-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_orcamentovenda_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada'), ('SUBSTITUIDA', 'Substituída')], default='FINALIZADA', max_length=20),
        ),
    ]
