# Generated by Django 5.2.5 on 2025-10-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
