# Generated by Django 5.2.5 on 2025-10-24 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_payableaccount_external_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='user_type',
            field=models.CharField(choices=[('BPO', 'BPO Admin'), ('CLIENTE', 'Cliente Final')], default='CLIENTE', max_length=10, verbose_name='Tipo de Conta'),
        ),
        migrations.CreateModel(
            name='BPOClientLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bpo_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_clients', to=settings.AUTH_USER_MODEL, verbose_name='BPO Admin (Usuário Mestre)')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='managed_by_bpo', to=settings.AUTH_USER_MODEL, verbose_name='Cliente (Usuário Gerenciado)')),
            ],
            options={
                'verbose_name': 'Link BPO-Cliente',
                'verbose_name_plural': 'Links BPO-Cliente',
                'unique_together': {('bpo_admin', 'client')},
            },
        ),
    ]
