# Generated by Django 5.2.5 on 2025-10-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_subscription_user_type_bpoclientlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='employee_limit',
            field=models.PositiveIntegerField(default=0, verbose_name='Limite de Funcionários Adicionais'),
        ),
    ]
