# Generated by Django 5.2.5 on 2025-10-25 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_subscription_employee_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyUserLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_owner_link', to=settings.AUTH_USER_MODEL, verbose_name='Funcionário')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL, verbose_name='Dono da Licença')),
            ],
            options={
                'verbose_name': 'Vínculo Dono-Funcionário',
                'verbose_name_plural': 'Vínculos Dono-Funcionário',
                'unique_together': {('owner', 'employee')},
            },
        ),
    ]
