# Generated by Django 5.2.5 on 2025-10-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_alter_category_options_category_category_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payableaccount',
            name='fitid',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ID da Transação (FITID)'),
        ),
        migrations.AddField(
            model_name='receivableaccount',
            name='fitid',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ID da Transação (FITID)'),
        ),
    ]
