# Generated by Django 5.2.5 on 2025-11-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_alter_category_unique_together_category_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuserlink',
            name='can_access_commercial',
            field=models.BooleanField(default=True, verbose_name='Acesso ao Módulo Comercial'),
        ),
        migrations.AddField(
            model_name='companyuserlink',
            name='can_access_financial',
            field=models.BooleanField(default=True, verbose_name='Acesso ao Módulo Financeiro'),
        ),
    ]
