# Generated by Django 5.2.5 on 2025-11-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_companyuserlink_can_access_commercial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuserlink',
            name='can_access_commercial',
            field=models.BooleanField(default=False, verbose_name='Acesso ao Módulo Comercial'),
        ),
        migrations.AlterField(
            model_name='companyuserlink',
            name='can_access_financial',
            field=models.BooleanField(default=False, verbose_name='Acesso ao Módulo Financeiro'),
        ),
    ]
