# Generated by Django 5.2.5 on 2025-11-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_alter_companyuserlink_can_access_commercial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='has_commercial_module',
            field=models.BooleanField(default=True, verbose_name='Possui Módulo Comercial?'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='has_financial_module',
            field=models.BooleanField(default=True, verbose_name='Possui Módulo Financeiro?'),
        ),
    ]
