# Generated by Django 5.2.5 on 2025-11-07 17:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_subscription_has_commercial_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='opening_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Abertura'),
        ),
    ]
