# Generated by Django 5.2.5 on 2025-11-14 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_bankaccount_opening_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnuncioGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título (Opcional)')),
                ('mensagem', models.TextField(verbose_name='Mensagem do Anúncio')),
                ('link_url', models.URLField(blank=True, help_text='Ex: /nova-feature/ ou https://site.com/promo', null=True, verbose_name='URL do Link (Opcional)')),
                ('is_active', models.BooleanField(default=False, help_text='Apenas UM anúncio pode estar ativo por vez. O mais recente será exibido.', verbose_name='Está Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Anúncio Global',
                'verbose_name_plural': 'Anúncios Globais',
                'ordering': ['-created_at'],
            },
        ),
    ]
