# Generated by Django 5.2.5 on 2025-11-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_anuncioglobal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payableaccount',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='receivables/%Y/%m/%d/'),
        ),
    ]
