# Generated by Django 5.2.5 on 2025-11-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_receivableaccount_file_alter_payableaccount_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyuserlink',
            name='can_access_commercial',
        ),
        migrations.RemoveField(
            model_name='companyuserlink',
            name='can_access_financial',
        ),
        migrations.AddField(
            model_name='companyuserlink',
            name='can_access_cadastros_comercial',
            field=models.BooleanField(default=False, verbose_name='Acesso a Cadastros (Comercial)'),
        ),
        migrations.AddField(
            model_name='companyuserlink',
            name='can_access_clientes_financeiro',
            field=models.BooleanField(default=False, verbose_name='Acesso a Clientes (Financeiro)'),
        ),
        migrations.AddField(
            model_name='companyuserlink',
            name='can_access_contas_pagar',
            field=models.BooleanField(default=False, verbose_name='Acesso a Contas a Pagar'),
        ),
        migrations.AddField(
            model_name='companyuserlink',
            name='can_access_contas_receber',
            field=models.BooleanField(default=False, verbose_name='Acesso a Contas a Receber'),
        ),
        migrations.AddField(
            model_name='companyuserlink',
            name='can_access_contratos',
            field=models.BooleanField(default=False, verbose_name='Acesso a Gestão de Contratos'),
        ),
        migrations.AddField(
            model_name='companyuserlink',
            name='can_access_fornecedores',
            field=models.BooleanField(default=False, verbose_name='Acesso a Fornecedores'),
        ),
        migrations.AddField(
            model_name='companyuserlink',
            name='can_access_metas_comerciais',
            field=models.BooleanField(default=False, verbose_name='Acesso a Gestão de Metas'),
        ),
        migrations.AddField(
            model_name='companyuserlink',
            name='can_access_notas_fiscais',
            field=models.BooleanField(default=False, verbose_name='Acesso a Notas Fiscais'),
        ),
        migrations.AddField(
            model_name='companyuserlink',
            name='can_access_orcamento_anual',
            field=models.BooleanField(default=False, verbose_name='Acesso a Orçamento Anual'),
        ),
        migrations.AddField(
            model_name='companyuserlink',
            name='can_access_orcamentos_venda',
            field=models.BooleanField(default=False, verbose_name='Acesso a Orçamentos'),
        ),
        migrations.AddField(
            model_name='companyuserlink',
            name='can_access_painel_financeiro',
            field=models.BooleanField(default=False, verbose_name='Acesso a Painel Financeiro (Dashboards)'),
        ),
        migrations.AddField(
            model_name='companyuserlink',
            name='can_access_painel_vendas',
            field=models.BooleanField(default=False, verbose_name='Acesso a Painel de Vendas'),
        ),
        migrations.AddField(
            model_name='companyuserlink',
            name='can_access_precificacao',
            field=models.BooleanField(default=False, verbose_name='Acesso a Precificação'),
        ),
        migrations.AddField(
            model_name='companyuserlink',
            name='can_access_tarefas',
            field=models.BooleanField(default=False, verbose_name='Acesso a Gestão de Tarefas'),
        ),
        migrations.AddField(
            model_name='companyuserlink',
            name='can_access_vendas',
            field=models.BooleanField(default=False, verbose_name='Acesso a Vendas'),
        ),
    ]
