# Generated by Django 5.2.5 on 2025-11-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_remove_companyuserlink_can_access_commercial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuserlink',
            name='can_access_home',
            field=models.BooleanField(default=True, verbose_name='Acesso à Home'),
        ),
    ]
