# Generated by Django 5.2.5 on 2025-11-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_companyuserlink_can_access_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_municipio',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Cód. Município (IBGE)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='logradouro',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Logradouro (Rua, Av.)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='razao_social',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Razão Social (se PJ)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='produtoservico',
            name='cfop_padrao',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='CFOP Padrão'),
        ),
        migrations.AddField(
            model_name='produtoservico',
            name='ncm',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='NCM'),
        ),
        migrations.AddField(
            model_name='produtoservico',
            name='origem',
            field=models.CharField(default='0', max_length=1, verbose_name='Origem (0=Nacional)'),
        ),
        migrations.AddField(
            model_name='produtoservico',
            name='unidade_medida',
            field=models.CharField(default='UN', max_length=6, verbose_name='Unidade (Ex: UN, CX, PC)'),
        ),
    ]
