# Generated by Django 5.2.5 on 2025-11-18 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_cliente_bairro_cliente_cep_cliente_cidade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtoservico',
            options={'verbose_name': 'Produto ou Serviço', 'verbose_name_plural': 'Produtos e Serviços'},
        ),
        migrations.AlterField(
            model_name='produtoservico',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='produtoservico',
            constraint=models.UniqueConstraint(fields=('user', 'codigo'), name='unique_codigo_per_user'),
        ),
    ]
