# Generated by Django 5.2.5 on 2025-11-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_alter_produtoservico_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoservico',
            name='codigo_servico',
            field=models.CharField(blank=True, help_text='Ex: 17.06 para Propaganda, 1.03 para TI. Apenas números.', max_length=20, null=True, verbose_name='Cód. Serviço (LC116)'),
        ),
    ]
