# Generated by Django 5.2.5 on 2025-11-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_produtoservico_codigo_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='codigo_municipio',
            field=models.CharField(blank=True, help_text='Ex: 3106200 para Belo Horizonte', max_length=7, null=True, verbose_name='Cód. Município (IBGE)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='inscricao_municipal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Municipal'),
        ),
    ]
