# Generated by Django 5.2.5 on 2025-11-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_companyprofile_codigo_municipio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
