# Generated by Django 5.2.5 on 2025-11-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_alter_cliente_cpf_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='certificado_digital',
            field=models.FileField(blank=True, null=True, upload_to='certificados/', verbose_name='Certificado Digital (A1 .pfx)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='senha_certificado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Senha do Certificado'),
        ),
    ]
