# Generated by Django 5.2.5 on 2025-11-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_companyprofile_certificado_digital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='aliquota_iss',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Alíquota padrão para serviços. Ex: 2.00 para 2%.', max_digits=5, verbose_name='Alíquota ISS (%)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='enviar_email_automatico',
            field=models.BooleanField(default=True, verbose_name='Enviar e-mail automático para o cliente?'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='regime_tributario',
            field=models.CharField(choices=[('1', 'Simples Nacional'), ('2', 'Simples Nacional (Excesso de Sublimite)'), ('3', 'Regime Normal (Lucro Presumido/Real)'), ('4', 'MEI (Microempreendedor Individual)')], default='1', max_length=1, verbose_name='Regime Tributário'),
        ),
    ]
