# Generated by Django 5.2.5 on 2025-11-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_companyprofile_aliquota_iss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual'),
        ),
    ]
