# Generated by Django 5.2.5 on 2025-11-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_companyprofile_inscricao_estadual'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='indicador_inscricao_estadual',
            field=models.CharField(choices=[('1', 'Contribuinte ICMS (Tem I.E.)'), ('2', 'Contribuinte Isento (Tem I.E. mas é isento)'), ('9', 'Não Contribuinte (Pessoa Física ou Prestador de Serviço)')], default='9', max_length=1, verbose_name='Indicador I.E.'),
        ),
    ]
