# Generated by Django 5.2.5 on 2025-11-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_alter_companyprofile_regime_especial_tributacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='incentivador_cultural',
            field=models.BooleanField(default=False, verbose_name='Incentivador Cultural?'),
        ),
    ]
