# Generated by Django 5.2.5 on 2025-11-22 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_companyprofile_incentivador_cultural'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='regime_especial_tributacao',
            field=models.CharField(blank=True, choices=[('0', 'Nenhum'), ('1', 'Microempresa Municipal'), ('2', 'Estimativa'), ('3', 'Sociedade de Profissionais'), ('4', 'Cooperativa'), ('5', 'MEI - Simples Nacional'), ('6', 'ME EPP - Simples Nacional')], default='0', help_text="Se ocorrer erro E327, verifique este campo. MEI geralmente usa '6 - ME EPP' ou '5 - MEI'. Consulte seu contador.", max_length=1, verbose_name='Regime Especial de Tributação (NFS-e)'),
        ),
    ]
