# Generated by Django 5.2.5 on 2025-11-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_alter_companyprofile_regime_especial_tributacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro'),
        ),
    ]
