# Generated by Django 5.2.5 on 2025-11-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_companyprofile_numero_alter_companyprofile_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='arquivo_logo',
            field=models.FileField(blank=True, null=True, upload_to='logos/', verbose_name='Logotipo da Empresa'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='proximo_numero_nfe',
            field=models.PositiveIntegerField(default=1, verbose_name='Próximo Nº NFe (Produto)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='proximo_numero_nfse',
            field=models.PositiveIntegerField(default=1, verbose_name='Próximo Nº NFS-e (Serviço)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='serie_nfe',
            field=models.CharField(default='1', max_length=3, verbose_name='Série NFe'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='serie_nfse',
            field=models.CharField(default='1', max_length=5, verbose_name='Série NFS-e'),
        ),
    ]
