# Generated by Django 5.2.5 on 2025-11-29 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_companyprofile_arquivo_logo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificacaoAutomatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(help_text="Termo para identificar (ex: 'Uber', 'Cemig')", max_length=200)),
                ('dre_area', models.CharField(choices=[('NAO_CONSTAR', 'Não constar DRE'), ('DEDUCAO', 'Dedução da Receita Bruta'), ('CUSTOS', 'Custos CSP/CMV'), ('OPERACIONAL', 'Despesas Operacionais'), ('DEPRECIACAO', 'Depreciação e Amortização'), ('NAO_OPERACIONAL', 'Não Operacional'), ('TRIBUTACAO', 'IRPJ e CSLL (Tributação)'), ('DISTRIBUICAO', 'Distribuição de Lucro Sócios'), ('BRUTA', 'Receitas Brutas')], max_length=50)),
                ('tipo', models.CharField(choices=[('PAYABLE', 'Contas a Pagar'), ('RECEIVABLE', 'Contas a Receber')], max_length=20)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Regra de Classificação',
                'verbose_name_plural': 'Regras de Classificação',
                'unique_together': {('user', 'termo', 'tipo')},
            },
        ),
    ]
