# Generated by Django 5.2.5 on 2025-12-01 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_alter_classificacaoautomatica_dre_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificacaoautomatica',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.bankaccount'),
        ),
    ]
