# Generated by Django 5.2.5 on 2025-12-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_classificacaoautomatica_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificacaoautomatica',
            name='dre_area',
            field=models.CharField(choices=[('NAO_CONSTAR', 'Não constar DRE'), ('BRUTA', 'Receitas Brutas (+)'), ('DEDUCAO', 'Dedução da Receita Bruta (-)'), ('CUSTOS', 'Custos CSP/CMV (-)'), ('OPERACIONAL', 'Despesas Operacionais (-)'), ('DEPRECIACAO', 'Depreciação e Amortização (-)'), ('NAO_OPERACIONAL', 'Despesas Não Operacionais (-)'), ('RETIRADA_SOCIOS', 'Retirada de Sócios (-)'), ('APORTE_SOCIOS', 'Aporte Financeiro (+)'), ('OUTRAS_RECEITAS', 'Outras Receitas - Aporte/Financeiro (+)'), ('TRIBUTACAO', 'IRPJ e CSLL (Tributação) (-)'), ('DISTRIBUICAO', 'Distribuição de Lucro Sócios (-)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payableaccount',
            name='dre_area',
            field=models.CharField(choices=[('NAO_CONSTAR', 'Não constar DRE'), ('BRUTA', 'Receitas Brutas (+)'), ('DEDUCAO', 'Dedução da Receita Bruta (-)'), ('CUSTOS', 'Custos CSP/CMV (-)'), ('OPERACIONAL', 'Despesas Operacionais (-)'), ('DEPRECIACAO', 'Depreciação e Amortização (-)'), ('NAO_OPERACIONAL', 'Despesas Não Operacionais (-)'), ('RETIRADA_SOCIOS', 'Retirada de Sócios (-)'), ('APORTE_SOCIOS', 'Aporte Financeiro (+)'), ('OUTRAS_RECEITAS', 'Outras Receitas - Aporte/Financeiro (+)'), ('TRIBUTACAO', 'IRPJ e CSLL (Tributação) (-)'), ('DISTRIBUICAO', 'Distribuição de Lucro Sócios (-)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='receivableaccount',
            name='dre_area',
            field=models.CharField(choices=[('NAO_CONSTAR', 'Não constar DRE'), ('BRUTA', 'Receitas Brutas (+)'), ('DEDUCAO', 'Dedução da Receita Bruta (-)'), ('CUSTOS', 'Custos CSP/CMV (-)'), ('OPERACIONAL', 'Despesas Operacionais (-)'), ('DEPRECIACAO', 'Depreciação e Amortização (-)'), ('NAO_OPERACIONAL', 'Despesas Não Operacionais (-)'), ('RETIRADA_SOCIOS', 'Retirada de Sócios (-)'), ('APORTE_SOCIOS', 'Aporte Financeiro (+)'), ('OUTRAS_RECEITAS', 'Outras Receitas - Aporte/Financeiro (+)'), ('TRIBUTACAO', 'IRPJ e CSLL (Tributação) (-)'), ('DISTRIBUICAO', 'Distribuição de Lucro Sócios (-)')], max_length=50),
        ),
    ]
