# Generated by Django 5.2.5 on 2025-12-07 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0069_alter_classificacaoautomatica_dre_area_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.cliente'),
        ),
        migrations.CreateModel(
            name='FechamentoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo Inicial (Fundo de Troco)')),
                ('total_vendas_dinheiro', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_vendas_pix', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_vendas_cartao', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_saidas_sangrias', models.DecimalField(decimal_places=2, default=0, help_text='Contas pagas em dinheiro do caixa', max_digits=12)),
                ('saldo_final_esperado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo Esperado na Gaveta')),
                ('saldo_final_informado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Saldo Contado na Gaveta')),
                ('diferenca', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Diferença (Quebra de Caixa)')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado')], default='ABERTO', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fechamento de Caixa',
                'verbose_name_plural': 'Fechamentos de Caixa',
                'ordering': ['-data_abertura'],
            },
        ),
    ]
