# Generated by Django 5.2.5 on 2025-12-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_alter_venda_cliente_fechamentocaixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuserlink',
            name='can_access_pdv',
            field=models.BooleanField(default=False, verbose_name='Acesso ao PDV (Frente de Caixa)'),
        ),
    ]
