# Generated by Django 5.2.5 on 2025-12-09 01:23

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_companyuserlink_can_access_pdv'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255, verbose_name='Client ID')),
                ('client_secret', models.CharField(max_length=255, verbose_name='Client Secret')),
                ('certificado_crt', models.FileField(upload_to=accounts.models.upload_cert_path, verbose_name='Arquivo .crt')),
                ('chave_key', models.FileField(upload_to=accounts.models.upload_cert_path, verbose_name='Arquivo .key')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inter_creds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
