# Generated by Django 5.2.5 on 2025-12-12 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0073_mercadopagocredentials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsaasCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=1024, verbose_name='Chave de API (API Key)')),
                ('is_sandbox', models.BooleanField(default=True, verbose_name='Ambiente de Testes (Sandbox)?')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asaas_creds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
