# Generated by Django 5.2.5 on 2025-12-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0074_asaascredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='ID do Cliente no Stripe', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='ID da Assinatura no Stripe', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Ativa'), ('past_due', 'Pagamento Pendente'), ('canceled', 'Cancelada'), ('expired', 'Expirada')], default='expired', max_length=20),
        ),
    ]
