# Generated by Django 5.2.5 on 2025-12-13 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0075_subscription_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='client_limit',
            field=models.PositiveIntegerField(default=1, verbose_name='Limite de Clientes/CNPJs'),
        ),
    ]
