# Generated by Django 5.2.5 on 2025-12-14 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0077_omiecredentials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NiboCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_token', models.CharField(max_length=500, verbose_name='API Token')),
                ('organization_id', models.CharField(help_text='O ID da sua empresa na URL do Nibo ou API.', max_length=100, verbose_name='ID da Empresa (Organization ID)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nibo_creds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
