# Generated by Django 5.2.5 on 2026-01-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0079_tinycredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuserlink',
            name='can_access_fluxo_caixa',
            field=models.BooleanField(default=False, verbose_name='Acesso a Fluxo de Caixa'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Ativa'), ('trial', 'Em Teste Grátis'), ('past_due', 'Pagamento Pendente'), ('canceled', 'Cancelada'), ('expired', 'Expirada')], default='expired', max_length=20),
        ),
    ]
