# Generated by Django 5.2.5 on 2026-01-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0080_companyuserlink_can_access_fluxo_caixa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuserlink',
            name='can_access_crm',
            field=models.BooleanField(default=False, verbose_name='Acesso ao CRM / Pipeline'),
        ),
    ]
