# Generated by Django 5.2.5 on 2026-01-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0081_companyuserlink_can_access_crm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='cnpj',
            field=models.CharField(max_length=18, null=True, unique=True, verbose_name='CNPJ'),
        ),
    ]
