# Generated by Django 5.2.5 on 2026-01-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0082_alter_companyprofile_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='dia_vencimento',
            field=models.PositiveIntegerField(default=10, verbose_name='Dia da Cobrança'),
        ),
        migrations.AddField(
            model_name='contract',
            name='financeiro_gerado',
            field=models.BooleanField(default=False, verbose_name='Financeiro Gerado?'),
        ),
        migrations.AddField(
            model_name='contract',
            name='frequencia_pagamento',
            field=models.CharField(choices=[('MENSAL', 'Mensal'), ('UNICO', 'Único')], default='MENSAL', max_length=10, verbose_name='Frequência'),
        ),
        migrations.AddField(
            model_name='contract',
            name='quantidade_parcelas',
            field=models.PositiveIntegerField(default=1, verbose_name='Qtd. Parcelas / Meses'),
        ),
        migrations.AddField(
            model_name='contract',
            name='reajuste_percentual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Reajuste (%)'),
        ),
    ]
