# Generated by Django 5.2.5 on 2026-01-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0084_centrocusto_payableaccount_centro_custo'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='has_fiscal_module',
            field=models.BooleanField(default=False, verbose_name='Possui Módulo Fiscal (NFe/NFSe)?'),
        ),
    ]
