# Generated by Django 5.2.5 on 2026-01-28 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0086_classificacaoautomatica_centro_custo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payableaccount',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.bankaccount'),
        ),
        migrations.AlterField(
            model_name='receivableaccount',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.bankaccount'),
        ),
    ]
