# Generated by Django 5.2.5 on 2026-01-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0087_alter_payableaccount_bank_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='aliquota_iss',
            field=models.DecimalField(decimal_places=4, default=2.0, help_text='Alíquota padrão para serviços. Ex: 2.00 para 2%.', max_digits=7, verbose_name='Alíquota ISS (%)'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Inscrição Estadual'),
        ),
    ]
