# Generated by Django 5.2.5 on 2026-02-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0088_alter_companyprofile_aliquota_iss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='asaas_api_key',
            field=models.CharField(blank=True, help_text='Chave gerada para transacionar em nome desta subconta', max_length=255, null=True, verbose_name='API Key da Subconta'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='asaas_subaccount_id',
            field=models.CharField(blank=True, help_text='Identificador da conta (ex: adp_...)', max_length=100, null=True, verbose_name='ID da Subconta Asaas'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='asaas_wallet_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Wallet ID Asaas'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='provider_fiscal',
            field=models.CharField(choices=[('FOCUS', 'Focus NFe'), ('ASAAS', 'Asaas')], default='FOCUS', max_length=20, verbose_name='Provedor Fiscal Ativo'),
        ),
    ]
