# Generated by Django 5.2.5 on 2026-02-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0089_companyprofile_asaas_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='provider_fiscal',
            field=models.CharField(blank=True, choices=[('FOCUS', 'Focus NFe'), ('ASAAS', 'Asaas')], default='FOCUS', max_length=20, verbose_name='Provedor Fiscal Ativo'),
        ),
    ]
