# Generated by Django 5.2.5 on 2026-02-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0090_alter_companyprofile_provider_fiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='asaas_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
