# Generated by Django 5.2.5 on 2026-02-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0091_cliente_asaas_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payableaccount',
            name='recurrence_group_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='payableaccount',
            name='recurrence_index',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Índice da Recorrência'),
        ),
        migrations.AddField(
            model_name='receivableaccount',
            name='recurrence_group_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='receivableaccount',
            name='recurrence_index',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Índice da Recorrência'),
        ),
    ]
