# Generated by Django 5.2.5 on 2026-02-13 19:49

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0093_coracredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='coracredentials',
            name='certificado',
            field=models.FileField(blank=True, help_text='Upload do arquivo certificate.pem', null=True, upload_to=accounts.models.upload_cora_cert),
        ),
        migrations.AddField(
            model_name='coracredentials',
            name='chave_privada',
            field=models.FileField(blank=True, help_text='Upload do arquivo private.key', null=True, upload_to=accounts.models.upload_cora_cert),
        ),
    ]
