# Generated by Django 5.2.5 on 2026-02-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0095_sicredicredentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sicredicredentials',
            name='partner_id',
            field=models.CharField(blank=True, help_text='Chave do Parceiro fornecida pelo Sicredi', max_length=255, null=True),
        ),
    ]
