# Generated by Django 5.2.5 on 2026-01-03 16:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0079_tinycredentials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FunilEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('cor_hexa', models.CharField(default='#3498db', help_text='Cor da barra lateral do card', max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Etapa do Funil',
                'verbose_name_plural': 'Etapas do Funil',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Compra de 10 Pneus', max_length=150, verbose_name='Título da Oportunidade')),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('data_fechamento_estimada', models.DateField(blank=True, null=True)),
                ('probabilidade', models.PositiveIntegerField(default=50, help_text='Em % (0 a 100)')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=20)),
                ('status', models.CharField(choices=[('ABERTO', 'Em Aberto'), ('GANHO', 'Ganho (Venda Fechada)'), ('PERDIDO', 'Perdido'), ('CONGELADO', 'Congelado/Stand-by')], default='ABERTO', max_length=20)),
                ('motivo_perda', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades_crm', to='accounts.cliente')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades', to='crm.funiletapa')),
                ('orcamento_gerado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidade_origem', to='accounts.orcamentovenda')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades_crm', to='accounts.vendedor')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Interacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NOTA', 'Anotação'), ('LIGACAO', 'Ligação'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'E-mail'), ('REUNIAO', 'Reunião'), ('TAREFA', 'Tarefa Concluída')], default='NOTA', max_length=20)),
                ('descricao', models.TextField(verbose_name='Resumo da interação')),
                ('data_interacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('oportunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='crm.oportunidade')),
            ],
        ),
        migrations.CreateModel(
            name='OrigemLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.origemlead'),
        ),
    ]
