# Generated by Django 5.2.5 on 2026-01-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0079_tinycredentials'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidade',
            name='produtos_interesse',
            field=models.ManyToManyField(blank=True, related_name='interessados_crm', to='accounts.produtoservico'),
        ),
    ]
